spring:
  application:
    name: chimera-app-service
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/chimera
    username: postgres
    password: postgres
  validation:
    method:
      adapt-constraint-violations: true

chimera:
  initializer:
    tracked-cities: Krakow
  weather:
    scheduler:
      enabled: true
      initial-delay: "5s"
      fixed-delay: "5s"
