spring:
  application:
    name: chimera-app-flyway
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/chimera
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration/core,classpath:db/migration/ext
    clean-disabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: true
