services:

  postgres:
    image: postgres:18.1-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chimera
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  wiremock:
    image: wiremock/wiremock:3.13.2-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:1080:8080"
    volumes:
      - ./wiremock/__files:/home/wiremock/__files:ro
      - ./wiremock/mappings:/home/wiremock/mappings:ro
    command: ["--global-response-templating"]

volumes:
  postgres_data:
  mongo_config:
